/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:48:56 GMT 2018
 */

package ats;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BikeTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike((String) null, 3078.14075949942, point2D_Double0, (String) null);
      Bike bike1 = bike0.clone();
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(1, bike1.getSeats());
      assertEquals(1, bike0.getSeats());
      assertEquals(75.0, bike0.getSpeed(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike("ak+ &o%", (-3590.702940971), point2D_Double0, "N+");
      Bike bike1 = bike0.clone();
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(1, bike0.getSeats());
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(1, bike1.getSeats());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double((-2237.9935), 0.0);
      Bike bike0 = new Bike("", 0.0, point2D_Double0, "");
      Trip trip0 = new Trip();
      bike0.addTrip(trip0);
      // Undeclared exception!
      try { 
        bike0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
//         verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike((Bike) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("Bike", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike("", 141.33825, point2D_Double0, "\n---------\nFila de Espera : \n");
      Bike bike1 = new Bike(bike0);
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(1, bike0.getSeats());
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(1, bike1.getSeats());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double((-2237.9935), 0.0);
      Bike bike0 = new Bike("", 0.0, point2D_Double0, "");
      Bike bike1 = bike0.clone();
      assertEquals(1, bike1.getSeats());
      assertEquals(75.0, bike0.getSpeed(), 0.01);
      assertEquals(0.9, bike0.getPrice(), 0.01);
      assertEquals(75.0, bike1.getSpeed(), 0.01);
      assertEquals(0.9, bike1.getPrice(), 0.01);
      assertEquals(1, bike0.getSeats());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike("", 75.0, (Point2D.Double) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("Vehicle", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Bike bike0 = null;
      try {
        bike0 = new Bike();
        //fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

    @Test(timeout = 4000)
    public void test8()  throws Throwable  {
        Bike bike = new Bike();
        double x = bike.getSpeed();
        assertEquals(75.0, bike.getSpeed(), 0.01);

    }

    @Test(timeout = 4000)
    public void test9()  throws Throwable  {
        Point2D.Double x = new Point2D.Double(5, 8);
        Bike bike = new Bike("1",0.5,x,"ola");
        Bike b = new Bike(bike);

        Bike c = b.clone();


    }




}
