/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:39:30 GMT 2018
 */
package ats;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomProbabilisticDistributionTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomProbabilisticDistribution customProbabilisticDistribution0 = new CustomProbabilisticDistribution();
      customProbabilisticDistribution0.addValues(577, (-2502.929071));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CustomProbabilisticDistribution customProbabilisticDistribution0 = new CustomProbabilisticDistribution();
      customProbabilisticDistribution0.addValues(577, 577);
      int int0 = customProbabilisticDistribution0.pickNumber();
      assertEquals(577, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CustomProbabilisticDistribution customProbabilisticDistribution0 = new CustomProbabilisticDistribution();
      customProbabilisticDistribution0.addValues((-1525), 1302.8165);
      int int0 = customProbabilisticDistribution0.pickNumber();
      assertEquals((-1525), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CustomProbabilisticDistribution customProbabilisticDistribution0 = new CustomProbabilisticDistribution();
      customProbabilisticDistribution0.addValues(0, 0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CustomProbabilisticDistribution customProbabilisticDistribution0 = new CustomProbabilisticDistribution();
      int int0 = customProbabilisticDistribution0.pickNumber();
      assertEquals(0, int0);
  }
}
