/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:46:41 GMT 2018
 */

package ats;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DriverTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      Point2D.Double point2D_Double0 = new Point2D.Double(0L, 4105);
      Point2D.Double point2D_Double1 = new Point2D.Double();
      Trip trip0 = new Trip(4105, point2D_Double0, point2D_Double0, (Double) point2D_Double0.y, (Double) 4105.0, localDate0, "3,`HlQ;ct%b9u$8|=", "w3='%DHp.:YmnNDZ", "", 4105, (-1409), point2D_Double1, 1.0, 4105.0, (-237.5757562));
      driver0.addTrip(trip0);
      assertEquals(4105.0, driver0.getTotalDistance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      Boolean boolean0 = driver0.isAvailable();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(boolean0);
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay(4, 5);
      Boolean boolean0 = Boolean.valueOf(true);
      Driver driver0 = new Driver("c8TVh", "c8TVh", "c8TVh", "IkmC[", localDate0, 2481.2627, 5, boolean0, 0.0, (ArrayList<Trip>) null, 4, 0.0, (-691.2457112055141), "\u20AC", "\u20AC", 0.0);
      driver0.getVehicle();
      assertEquals(4, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(5.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.setVehicle("");
      driver0.getVehicle();
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours((-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver((String) null, (String) null, "", "", localDate0, (-1), (String) null);
      Double double0 = driver0.getTimeCompliance();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-1.0), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("Od_", "24", "]A\"h|/-^kC-!", "]A\"h|/-^kC-!", localDate0, 0.0, "1-Nf1x&yWleZn");
      Double double0 = driver0.getTimeCompliance();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, (double)double0, 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.setTimeCompliance(1);
      driver0.getTimeCompliance();
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Month month0 = Month.AUGUST;
      LocalDate localDate0 = MockLocalDate.of(1055, month0, 5);
      Boolean boolean0 = Boolean.FALSE;
      Driver driver0 = new Driver("s", "", "s", "s", localDate0, 0.0, 0.0, boolean0, (-887.0), (ArrayList<Trip>) null, (-1), 1055, 0.0, "s", "", (-2972.529424));
      driver0.addRating((-1));
      driver0.getRating();
      assertEquals(Double.NEGATIVE_INFINITY, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-3247L));
      Boolean boolean0 = Boolean.TRUE;
      Driver driver0 = new Driver("", "", "", "E+em@:/\tAGCICkZs", localDate0, (-3247L), (-3247L), boolean0, 625.72424461, (ArrayList<Trip>) null, 391, (-3247L), 391, "", "", 625.72424461);
      Double double0 = driver0.getRating();
      assertEquals(391, driver0.getNumberOfReviews());
      assertEquals((-3247.0), (double)double0, 0.01);
      assertEquals(625.72424461, driver0.getTimeCompliance(), 0.01);
      assertEquals(625.72424461, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.addRating(1);
      driver0.getRating();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.addRating(1);
      int int0 = driver0.getNumberOfReviews();
      assertEquals(20.0, driver0.getRating(), 0.01);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours((-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver((String) null, (String) null, "", "", localDate0, (-1), (String) null);
      driver0.setNumberOfReviews((-1));
      int int0 = driver0.getNumberOfReviews();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      driver0.setExp(1304);
      int int0 = driver0.getExp();
      assertEquals(1304, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      driver0.setExp((-1385));
      int int0 = driver0.getExp();
      assertEquals((-1385), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay(4, 5);
      Boolean boolean0 = Boolean.valueOf(true);
      Driver driver0 = new Driver("c8TVh", "c8TVh", "c8TVh", "IkmC[", localDate0, 2481.2627, 5, boolean0, 0.0, (ArrayList<Trip>) null, 4, 0.0, (-691.2457112055141), "\u20AC", "\u20AC", 0.0);
      driver0.setdeviation(3600.0);
      double double0 = driver0.getDeviation();
      assertEquals(3600.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Boolean boolean0 = Boolean.TRUE;
      Driver driver0 = new Driver("Driver", (String) null, "\nN\u00FAmero de classifica\u00E7\u00F5es : ", "\nN\u00FAmero de classifica\u00E7\u00F5es : ", localDate0, 35.433362, (String) null);
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Driver driver1 = new Driver("Driver", (String) null, (String) null, (String) null, localDate0, 0, 0, boolean0, 0.0, arrayList0, (-3080), 0, 0, (String) null, "Je@!?G[6y4)FVF+R", (-1869.0));
      Driver driver2 = new Driver(driver1);
      double double0 = driver2.getDeviation();
      assertEquals(35.433362, driver0.getTimeCompliance(), 0.01);
      assertEquals((-3080), driver1.getNumberOfReviews());
      assertEquals(0, driver2.getExp());
      assertEquals(0.0, driver2.getRating(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver1.getTimeCompliance(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals((-1869.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours((-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver((String) null, (String) null, "", "", localDate0, (-1), (String) null);
      driver0.getCompany();
      assertEquals((-1.0), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, 1525.0, 0L, boolean0, 0L, arrayList0, 0, 0, 2.0, "", "", 2.0);
      driver0.getCompany();
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(2.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Period period0 = Period.ofDays((-1950));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver(">^OIt`tL[/02/b%o:)", ">^OIt`tL[/02/b%o:)", ">^OIt`tL[/02/b%o:)", "V", localDate0, (-1694.6251621), "*w-");
      Driver driver1 = new Driver((String) null, "*w-", "*w-", ">^OIt`tL[/02/b%o:)", localDate0, (-612L), "V");
      driver0.equals(driver1);
      assertEquals(0.0, driver1.getDeviation(), 0.01);
      assertTrue(driver1.isAvailable());
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver1.getRating(), 0.01);
      assertEquals((-612.0), driver1.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Boolean boolean0 = Boolean.valueOf(true);
      Driver driver0 = new Driver("\nData de nascimento : ", "\nVe\u00EDculo : ", "\nData de nascimento : ", "><", localDate0, (-4407.813414344463), 1376.1281910431, boolean0, (-4407.813414344463), (ArrayList<Trip>) null, 1, 1376.1281910431, 0L, ") ---> (", ") ---> (", 0.0);
      Driver driver1 = driver0.clone();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver1.getExp());
      assertEquals((-4407.813414344463), driver0.getTimeCompliance(), 0.01);
      assertEquals(1, driver0.getNumberOfReviews());
      assertEquals(1376.1281910431, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Driver driver0 = new Driver("(m4IQj3Tx=7", "(m4IQj3Tx=7", "", "", localDate0, (-571.453565665), "");
      Point2D.Double point2D_Double0 = new Point2D.Double((-571.453565665), (-571.453565665));
      Trip trip0 = new Trip(1, point2D_Double0, point2D_Double0, (Double) (-571.453565665), (Double) (-571.453565665), localDate0, "(m4IQj3Tx=7", "", "wv(,A$dJr5]", (-942), 0.0, point2D_Double0, 0.0, (-2254.93426071633), (-4024.730498));
      driver0.addTrip(trip0);
      driver0.clone();
      assertEquals(3453.276932335, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Month month0 = Month.AUGUST;
      LocalDate localDate0 = MockLocalDate.of(1055, month0, 5);
      Boolean boolean0 = Boolean.FALSE;
      Driver driver0 = new Driver("s", "", "s", "s", localDate0, 0.0, 0.0, boolean0, (-887.0), (ArrayList<Trip>) null, (-1), 1055, 0.0, "s", "", (-2972.529424));
      driver0.addRating((-1));
      driver0.clone();
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.valueOf(true);
      Driver driver0 = new Driver("copB", "", "", "", localDate0, (-1985.9306288), "\nDisponibilidade : ");
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Driver driver1 = new Driver("", "", "", "copB", localDate0, 1214.08220395, 3600.0, boolean0, 3600.0, arrayList0, (-1051), 60.0, (-1985.9306288), "\nN\u00FAmero de classifica\u00E7\u00F5es : ", "", 3600.0);
      Driver driver2 = driver1.clone();
      assertTrue(driver0.isAvailable());
      assertEquals((-1985.9306288), driver0.getTimeCompliance(), 0.01);
      assertEquals((-1051), driver1.getNumberOfReviews());
      assertEquals(3600.0, driver2.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver2.getExp());
      assertEquals(3600.0, driver2.getRating(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(3600.0, driver1.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Period period0 = Period.ZERO;
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      Driver driver0 = new Driver((String) null, "X_O!$f9o`d19Wpri", "+YCS8luJaa/", "u(H}3", localDate0, (-1326.413), "\nGrau de cumprimento : ");
      driver0.setdeviation((-33.203));
      driver0.clone();
      assertEquals((-33.203), driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Period period0 = Period.ofWeeks((-1237));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("\nVe\u00EDculo : ", "\nVe\u00EDculo : ", "w|QhKAJ]t3>==*Ztzb6", "\nVe\u00EDculo : ", localDate0, (-2923.3264534539), "m:");
      // Undeclared exception!
      try { 
        driver0.setAvailability((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
//         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Period period0 = Period.ofDays((-1950));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver(">^OIt`tL[/02/b%o:)", ">^OIt`tL[/02/b%o:)", ">^OIt`tL[/02/b%o:)", "V", localDate0, (-1694.6251621), "*w-");
      Driver driver1 = new Driver((String) null, "*w-", "*w-", ">^OIt`tL[/02/b%o:)", localDate0, (-612L), "V");
      // Undeclared exception!
      try { 
        driver1.equals(driver0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Trip trip0 = new Trip();
      arrayList0.add(trip0);
      Driver driver0 = new Driver("cZa*n!<R3L9NJ~^", "c3Jt:`(dL#mo5", (String) null, "**", localDate0, 1.0, 2424.98597279537, boolean0, 1.0, arrayList0, 2042, 1.0, 1.0, ")%=/<+~1\"olbXEj/x", "**", 2042);
      // Undeclared exception!
      try { 
        driver0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      //   verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver("f} <?}", "f} <?}", "f} <?}", "f} <?}", (LocalDate) null, 0.0, "f} <?}");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
        // verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Boolean boolean0 = Boolean.FALSE;
      Driver driver0 = null;
      try {
        driver0 = new Driver("$NC\\=X(o:r49Ri", "", "a", "\nDesvio total : ", (LocalDate) null, 1.0, 1.0, boolean0, 0.0, (ArrayList<Trip>) null, 924, 1.0, 0.0, "az\t?", "\nClassifica\u00E7\u00E3o : ", 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
     //    verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver((Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
       //  verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      Double double0 = driver0.getRating();
      assertEquals(0.0, (double)double0, 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      double double0 = driver0.getDeviation();
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.getCompany();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      int int0 = driver0.getNumberOfReviews();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, int0);
      assertTrue(driver0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      int int0 = driver0.getExp();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0, int0);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("Fc", "*@jbdX1n6M9mf", "<f[1bQ5<xU", "", localDate0, 1684.618, "Client");
      driver0.getVehicle();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(1684.618, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("cZa*n!<R3L9NJ~^", "c3Jt:`(dL#mo5", (String) null, "**", localDate0, 1.0, 2424.98597279537, boolean0, 1.0, arrayList0, 2042, 1.0, 1.0, ")%=/<+~1\"olbXEj/x", "**", 2042);
      driver0.addRating(2042);
      driver0.getRating();
      assertEquals(1224, driver0.getExp());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      driver0.addRating(2);
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Month month0 = Month.DECEMBER;
      LocalDate localDate0 = MockLocalDate.of(1, month0, 1);
      Boolean boolean0 = Boolean.valueOf("G");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver((String) null, (String) null, "V=(#W@!>1e:", "nFwHSS7]Kq=", localDate0, (-5900.5319137698), 1058.0055788508032, boolean0, 0.0, arrayList0, 1, 1, 0.0, "GvEb7 ~kE", "3[nHQpEN9@(", (-358.0609369));
      // Undeclared exception!
      try { 
        driver0.addTrip((Trip) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
    //     verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("cZa*n!<R3L9NJ~^", "c3Jt:`(dL#mo5", (String) null, "**", localDate0, 1.0, 2424.98597279537, boolean0, 1.0, arrayList0, 2042, 1.0, 1.0, ")%=/<+~1\"olbXEj/x", "**", 2042);
      driver0.setAvailability(boolean0);
      assertEquals(2042.0, driver0.getDeviation(), 0.01);
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(2042, driver0.getNumberOfReviews());
      assertEquals(2424.98597279537, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nVe\u00EDculo : ", "\nVe\u00EDculo : ", "\nVe\u00EDculo : ", "\nVe\u00EDculo : ", localDate0, 1.8770954328205982, "\nVe\u00EDculo : ");
      driver0.equals(driver0);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(1.8770954328205982, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      driver0.setRating(1304);
      assertEquals(1304.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver();
//        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for MonthOfYear (valid values 1 - 12): 0
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      driver0.setExp(1304);
      driver0.clone();
      assertEquals(1304, driver0.getExp());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("aD]C{v`s!ro)4AX`}U", "aD]C{v`s!ro)4AX`}U", "w3='%DHp.:YmnNDZ", "aD]C{v`s!ro)4AX`}U", localDate0, 0L, "w3='%DHp.:YmnNDZ");
      String string0 = driver0.toString();
      assertEquals("Driver \nUtilizador - aD]C{v`s!ro)4AX`}U\neMail : aD]C{v`s!ro)4AX`}U\nPassword : w3='%DHp.:YmnNDZ\nMorada : aD]C{v`s!ro)4AX`}U\nData de nascimento : 1970-01-01\nDist\u00E2ncia Total : 0.0\nDinheiro gasto/ganho : 0.0\nN\u00FAmero de viagens :0\nDisponibilidade : true\nClassifica\u00E7\u00E3o : 0.0\nGrau de cumprimento : 0.0\nN\u00FAmero de classifica\u00E7\u00F5es : 0\nVe\u00EDculo : null\nDesvio total : 0.0\n", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("cZa*n!<R3L9NJ~^", "c3Jt:`(dL#mo5", (String) null, "**", localDate0, 1.0, 2424.98597279537, boolean0, 1.0, arrayList0, 2042, 1.0, 1.0, ")%=/<+~1\"olbXEj/x", "**", 2042);
      driver0.isAvailable();
      assertEquals(2042.0, driver0.getDeviation(), 0.01);
      assertEquals(2424.98597279537, driver0.getRating(), 0.01);
      assertEquals(2042, driver0.getNumberOfReviews());
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
  }
}
