/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:40:36 GMT 2018
 */

package ats;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelicopterTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Helicopter helicopter0 = new Helicopter("", 0.0, point2D_Double0, "");
      Helicopter helicopter1 = helicopter0.clone();
      assertEquals(110.0, helicopter1.getSpeed(), 0.01);
      assertEquals(3, helicopter1.getSeats());
      assertEquals(3, helicopter0.getSeats());
      assertEquals(8.5, helicopter1.getPrice(), 0.01);
      assertEquals(8.5, helicopter0.getPrice(), 0.01);
      assertEquals(110.0, helicopter0.getSpeed(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Helicopter helicopter0 = new Helicopter("2r;V*tlf", 724.30192, point2D_Double0, "2r;V*tlf");
      Helicopter helicopter1 = helicopter0.clone();
      assertEquals(3, helicopter0.getSeats());
      assertEquals(110.0, helicopter1.getSpeed(), 0.01);
      assertEquals(8.5, helicopter0.getPrice(), 0.01);
      assertEquals(110.0, helicopter0.getSpeed(), 0.01);
      assertEquals(8.5, helicopter1.getPrice(), 0.01);
      assertEquals(3, helicopter1.getSeats());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double((-3018.472254988408), (-3018.472254988408));
      Helicopter helicopter0 = new Helicopter("", (-1606.97), point2D_Double0, "s!)pk!3cssg");
      Trip trip0 = new Trip();
      helicopter0.addTrip(trip0);
      // Undeclared exception!
      try { 
        helicopter0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
       //  verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Helicopter helicopter0 = null;
      try {
        helicopter0 = new Helicopter("Helicopter", 0.0, (Point2D.Double) null, "Helicopter");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("Vehicle", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Helicopter helicopter0 = null;
      try {
        helicopter0 = new Helicopter((Helicopter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
        // verifyException("Helicopter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Helicopter helicopter0 = new Helicopter("Helicopter", 1908.2, point2D_Double0, "Helicopter");
      Helicopter helicopter1 = new Helicopter(helicopter0);
      assertEquals(110.0, helicopter0.getSpeed(), 0.01);
      assertEquals(8.5, helicopter0.getPrice(), 0.01);
      assertEquals(3, helicopter1.getSeats());
      assertEquals(8.5, helicopter1.getPrice(), 0.01);
      assertEquals(110.0, helicopter1.getSpeed(), 0.01);
      assertEquals(3, helicopter0.getSeats());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Helicopter helicopter0 = null;
      try {
        helicopter0 = new Helicopter();
//        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Point2D.Double point2D_Double0 = new Point2D.Double((-3018.472254988408), (-3018.472254988408));
      Helicopter helicopter0 = new Helicopter("", (-1606.97), point2D_Double0, "s!)pk!3cssg");
      Helicopter helicopter1 = helicopter0.clone();
      assertEquals(8.5, helicopter0.getPrice(), 0.01);
      assertEquals(110.0, helicopter0.getSpeed(), 0.01);
      assertEquals(110.0, helicopter1.getSpeed(), 0.01);
      assertEquals(3, helicopter0.getSeats());
      assertEquals(3, helicopter1.getSeats());
      assertEquals(8.5, helicopter1.getPrice(), 0.01);
  }
}
