/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:38:21 GMT 2018
 */

package ats;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RatingComparatorTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RatingComparator ratingComparator0 = new RatingComparator();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Boolean boolean0 = new Boolean(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver((String) null, (String) null, "nK,N/B|rYI@n#H; '", (String) null, localDate0, 0L, 0.0, boolean0, 4455.144258, arrayList0, 4458, 609.7376034805, 60.0, "nK,N/B|rYI@n#H; '", "", 60.0);
      // Undeclared exception!
      try { 
        ratingComparator0.compare(driver0, driver0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
       //  verifyException("RatingComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RatingComparator ratingComparator0 = new RatingComparator();
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("`", "`", "`", "`", localDate0, 674, "`");
      driver0.setRating(674);
      Driver driver1 = new Driver("`", "`", "`", "`", localDate0, 674, "`");
      int int0 = ratingComparator0.compare(driver1, driver0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RatingComparator ratingComparator0 = new RatingComparator();
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("`", "`", "`", "`", localDate0, 674, "`");
      driver0.setRating(674);
      Driver driver1 = new Driver("`", "`", "`", "`", localDate0, 674, "`");
      int int0 = ratingComparator0.compare(driver0, driver1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RatingComparator ratingComparator0 = new RatingComparator();
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("`", "`", "`", "`", localDate0, 674, "`");
      int int0 = ratingComparator0.compare(driver0, driver0);
      assertEquals(0, int0);
  }
}
