/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 04 16:44:14 GMT 2018
 */

package ats;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MoneyComparatorCTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MoneyComparatorC moneyComparatorC0 = new MoneyComparatorC();
      LocalDate localDate0 = MockLocalDate.now();
      Client client0 = new Client((String) null, (String) null, (String) null, (String) null, localDate0);
      // Undeclared exception!
      try { 
        moneyComparatorC0.compare(client0, client0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
        // verifyException("MoneyComparatorC", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MoneyComparatorC moneyComparatorC0 = new MoneyComparatorC();
      LocalDate localDate0 = MockLocalDate.now();
      Client client0 = new Client("T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", localDate0);
      Client client1 = new Client(client0);
      client1.setMoney(49L);
      int int0 = moneyComparatorC0.compare(client0, client1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MoneyComparatorC moneyComparatorC0 = new MoneyComparatorC();
      LocalDate localDate0 = MockLocalDate.now();
      Client client0 = new Client("T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", localDate0);
      Client client1 = new Client(client0);
      client1.setMoney(49L);
      int int0 = moneyComparatorC0.compare(client1, client0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MoneyComparatorC moneyComparatorC0 = new MoneyComparatorC();
      LocalDate localDate0 = MockLocalDate.now();
      Client client0 = new Client("T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", "T5!Cwk6J#0z=Z9je", localDate0);
      int int0 = moneyComparatorC0.compare(client0, client0);
      assertEquals(0, int0);
  }
}
