/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 22:19:58 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.time.chrono.MinguoDate;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.evosuite.runtime.mock.java.time.chrono.MockMinguoDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Driver_ESTest extends Driver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Driver driver0 = new Driver("", "", "", "", localDate0, 2.0, "L*=@5EMfu9XT!<!");
      Point2D.Double point2D_Double0 = new Point2D.Double((-1105), 2.0);
      Point2D.Double point2D_Double1 = new Point2D.Double();
      Trip trip0 = new Trip((-1105), point2D_Double0, point2D_Double1, (Double) 2.0, (Double) point2D_Double0.y, localDate0, "h:", "GH&StiT#o8{$", "h:", (-1105), 2.0, point2D_Double1, 2.0, 2.0, (-1105));
      driver0.addTrip(trip0);
      assertEquals(2210.0036199065376, driver0.getTotalDistance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nTrip id : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, (-1.0), 0.0, boolean0, 0.0, arrayList0, 0, 0.0, 1, "\nTrip id : ", "", 0);
      driver0.isAvailable();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nTrip id : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, (-1.0), 0.0, boolean0, 0.0, arrayList0, 0, 0.0, 1, "\nTrip id : ", "", 0);
      driver0.getVehicle();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2415L);
      Boolean boolean0 = Boolean.valueOf(false);
      Driver driver0 = new Driver("", "\nDesvio total : ", "B8FT%", (String) null, localDate0, 2415L, 0.0, boolean0, 2415L, (ArrayList<Trip>) null, 0, 0.0, 607.0, "", "B8FT%", (-1173.048862088));
      driver0.getVehicle();
      assertEquals(2415.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals((-1173.048862088), driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      Double double0 = driver0.getTimeCompliance();
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, (double)double0, 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver((String) null, "\nPosi\u00E7\u00E3o : (", (String) null, "D^Ou^pLW4", localDate0, 320.002, "\nPosi\u00E7\u00E3o : (");
      Double double0 = driver0.getTimeCompliance();
      assertEquals(320.002, (double)double0, 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MinguoDate minguoDate0 = MockMinguoDate.now();
      LocalDate localDate0 = MockLocalDate.from(minguoDate0);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("`", "", "Driver", "`", localDate0, 346.12, 0.0, boolean0, 3929.545, arrayList0, (-703), (-2302.0), 3929.545, "", "Co'ic7", 3929.545);
      driver0.addRating((-703));
      driver0.getRating();
      assertEquals((-702), driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1300L));
      Driver driver0 = new Driver("\nMorada : ", "", "", "", localDate0, 0.0, "");
      driver0.addRating(2885);
      driver0.getRating();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1784L));
      Driver driver0 = new Driver("\nDisponibilidade : ", "Uv)l7\".V#sp~QO", "\nDisponibilidade : ", "Uv)l7\".V#sp~QO", localDate0, (-1784L), "Uv)l7\".V#sp~QO");
      driver0.addRating((-1053));
      driver0.getRating();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(20);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("<gIF9R9J", "<gIF9R9J", "ib.h]r9", "4oIu'iDazO~WYgWQ", localDate0, 12.0776328, 12.0776328, boolean0, 0.0, arrayList0, 20, 4.0, 12.0776328, "eC/_v[6EH)J-*RP", "p_& *I}", 20);
      int int0 = driver0.getNumberOfReviews();
      assertEquals(20, int0);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(20.0, driver0.getDeviation(), 0.01);
      assertEquals(12.0776328, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds((-10));
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("<gIF9R9J", "<gIF9R9J", "ib.h]r9", "4oIu'iDazO~WYgWQ", localDate0, 12.0776328, 12.0776328, boolean0, 0.0, arrayList0, (-10), 4.0, 12.0776328, "eC/_v[6EH)J-*RP", "p_& *I}", (-10));
      int int0 = driver0.getNumberOfReviews();
      assertEquals(12.0776328, driver0.getRating(), 0.01);
      assertEquals((-10.0), driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals((-10), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      driver0.setExp(349);
      int int0 = driver0.getExp();
      assertEquals(349, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1784L));
      Driver driver0 = new Driver("\nDisponibilidade : ", "Uv)l7\".V#sp~QO", "\nDisponibilidade : ", "Uv)l7\".V#sp~QO", localDate0, (-1784L), "Uv)l7\".V#sp~QO");
      driver0.addRating((-1053));
      int int0 = driver0.getExp();
      assertEquals(1, driver0.getNumberOfReviews());
      assertEquals((-1057), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MinguoDate minguoDate0 = MockMinguoDate.now();
      LocalDate localDate0 = MockLocalDate.from(minguoDate0);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("`", "", "Driver", "`", localDate0, 346.12, 0.0, boolean0, 3929.545, arrayList0, (-703), (-2302.0), 3929.545, "", "Co'ic7", 3929.545);
      double double0 = driver0.getDeviation();
      assertEquals(3929.545, double0, 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(3929.545, driver0.getTimeCompliance(), 0.01);
      assertEquals((-703), driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      Driver driver0 = new Driver("JW+NHk{*=:/", "0Vh", "", "0Vh", localDate0, (-709.90899627), "0Vh");
      driver0.setdeviation((-2093.811594895186));
      double double0 = driver0.getDeviation();
      assertEquals((-2093.811594895186), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Period period0 = Period.ofYears((-577));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("g9+J2^e|", "", "g9+J2^e|", (String) null, localDate0, (-577), (String) null);
      driver0.getCompany();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-577.0), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "\nDist\u00E2ncia Total : ", "+I:5", "\nDist\u00E2ncia Total : ", localDate0, 0.0, "\nDist\u00E2ncia Total : ");
      driver0.getCompany();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.valueOf("C&");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("*f[j", "", "", (String) null, localDate0, 0.0, 522.054, boolean0, 522.054, arrayList0, (-1), (-1), 1.0, "", "*f[j", 1.0);
      Driver driver1 = new Driver("(eq6>y]Bc{l", "*f[j", "", "e$", localDate0, 555.5, (-1), boolean0, 2321.5800659305, arrayList0, 0, 555.5, 527.00808964309, (String) null, "~IPD36^9Qg.", 555.5);
      driver0.equals(driver1);
      assertEquals((-1), driver0.getNumberOfReviews());
      assertEquals(555.5, driver1.getDeviation(), 0.01);
      assertEquals(2321.5800659305, driver1.getTimeCompliance(), 0.01);
      assertEquals((-1.0), driver1.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nTrip id : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, (-1.0), 0.0, boolean0, 0.0, arrayList0, 0, 0.0, 1, "\nTrip id : ", "", 0);
      Driver driver1 = driver0.clone();
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver1.getExp());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1300L));
      Driver driver0 = new Driver("\nMorada : ", "", "", "", localDate0, 0.0, "");
      Point2D.Double point2D_Double0 = new Point2D.Double(0.0, 0);
      Trip trip0 = new Trip(0, point2D_Double0, point2D_Double0, (Double) 0.0, (Double) 0.0, localDate0, "\nMorada : ", "", "x.'JA[Uu", 0, 0.0, point2D_Double0, 4.0, 0.0, 0.0);
      driver0.addTrip(trip0);
      Driver driver1 = driver0.clone();
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver1.getTotalDistance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver1.getExp());
      assertTrue(driver1.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver1.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.valueOf("C&");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("(eq6>y]Bc{l", "*f[j", "", "e$", localDate0, 555.5, (-1), boolean0, 2321.5800659305, arrayList0, 0, 555.5, 527.00808964309, (String) null, "~IPD36^9Qg.", 555.5);
      Driver driver1 = driver0.clone();
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(2321.5800659305, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver1.getExp());
      assertEquals((-1.0), driver0.getRating(), 0.01);
      assertEquals(555.5, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1300L));
      Driver driver0 = new Driver("\nMorada : ", "", "", "", localDate0, 0.0, "");
      driver0.addRating(2885);
      driver0.clone();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1784L));
      Driver driver0 = new Driver("\nDisponibilidade : ", "Uv)l7\".V#sp~QO", "\nDisponibilidade : ", "Uv)l7\".V#sp~QO", localDate0, (-1784L), "Uv)l7\".V#sp~QO");
      driver0.addRating((-1053));
      driver0.clone();
      assertEquals((-21060.0), driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Boolean boolean0 = Boolean.valueOf("C&");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("*f[j", "", "", (String) null, localDate0, 0.0, 522.054, boolean0, 522.054, arrayList0, (-1), (-1), 1.0, "", "*f[j", 1.0);
      Driver driver1 = driver0.clone();
      assertEquals((-1), driver0.getNumberOfReviews());
      assertEquals(0, driver1.getExp());
      assertEquals(522.054, driver0.getTimeCompliance(), 0.01);
      assertEquals(522.054, driver0.getRating(), 0.01);
      assertEquals(1.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "F-\"QULrs;Ic82*", "H(oe>v|\"9Sx4AQu", "H(oe>v|\"9Sx4AQu", localDate0, 2.0, "F-\"QULrs;Ic82*");
      // Undeclared exception!
      try { 
        driver0.setAvailability((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("QTR52-", "QTR52-", "", "", localDate0, (-1925.39387913872), "");
      driver0.setEmail((String) null);
      // Undeclared exception!
      try { 
        driver0.equals(driver0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("QE#5w-");
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Trip trip0 = new Trip();
      arrayList0.add(trip0);
      Driver driver1 = new Driver("QE#5w-", "\nDisponibilidade : ", "\nDisponibilidade : ", "e=UW1r0;C*X!", localDate0, (-2720.0), (-1925.39387913872), boolean0, 0.0, arrayList0, 2, 2, 2015.0632852053, "\nEmail cliente : ", "QE#5w-", 1.0);
      // Undeclared exception!
      try { 
        driver1.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Trip", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver(":.6", "\nN\u00FAmero de viagens :", "X", "bJNI'", (LocalDate) null, 0.0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = null;
      try {
        driver0 = new Driver("", "", "hEs4M*S$4YvnGrQtW", "hEs4M*S$4YvnGrQtW", (LocalDate) null, (-1.0), (-424.61986168699), boolean0, (-424.61986168699), arrayList0, (-1), (-1), (-1.0), "", "", (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver((Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      Boolean boolean0 = driver0.isAvailable();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertTrue(boolean0);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      Double double0 = driver0.getRating();
      assertTrue(driver0.isAvailable());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-791.25360530683), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nTrip id : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, (-1.0), 0.0, boolean0, 0.0, arrayList0, 0, 0.0, 1, "\nTrip id : ", "", 0);
      double double0 = driver0.getDeviation();
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("DQDe[`t", "\nGrau de cumprimento : ", "\nGrau de cumprimento : ", (String) null, localDate0, 0.0, (String) null);
      Driver driver1 = new Driver(driver0);
      assertEquals(0, driver1.getExp());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver1.isAvailable());
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      driver0.getCompany();
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      int int0 = driver0.getNumberOfReviews();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nDist\u00E2ncia Total : ", "Trip", "+I:5", "Trip", localDate0, 0.0, "");
      int int0 = driver0.getExp();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, int0);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ZoneId zoneId0 = ZoneId.systemDefault();
      Clock clock0 = MockClock.tickSeconds(zoneId0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Driver driver0 = new Driver("\nGrau de cumprimento : ", "^BJO3Sy'3.mM$,", "^BJO3Sy'3.mM$,", "^BJO3Sy'3.mM$,", localDate0, (-1149.872198013192), "CA");
      Double double0 = driver0.getTimeCompliance();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals((-1149.872198013192), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", localDate0, 1.0, "");
      driver0.getVehicle();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      driver0.addRating(2);
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", localDate0, 1.0, "");
      // Undeclared exception!
      try { 
        driver0.addTrip((Trip) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("User", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", localDate0, 1.0, "");
      assertTrue(driver0.isAvailable());
      
      Boolean boolean0 = Boolean.valueOf(",OX$/t\f8B");
      driver0.setAvailability(boolean0);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      driver0.equals(driver0);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-791.25360530683), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1795L));
      Driver driver0 = new Driver("Jt*", "Jt*", "Jt*", "Jt*", localDate0, (-1795L), "Jt*");
      driver0.setdeviation((-1795L));
      driver0.clone();
      assertEquals((-1795.0), driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", localDate0, 1.0, "");
      driver0.setVehicle("LWL9i [.bEHv");
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      driver0.setRating(2015.0632852053);
      assertEquals(2015.0632852053, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      driver0.setNumberOfReviews((-1933));
      assertEquals((-1933), driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver();
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for MonthOfYear (valid values 1 - 12): 0
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver(",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", ",OX$/t\f8B", localDate0, 1.0, "");
      String string0 = driver0.toString();
      assertEquals("Driver \nUtilizador - ,OX$/t\f8B\neMail : ,OX$/t\f8B\nPassword : ,OX$/t\f8B\nMorada : ,OX$/t\f8B\nData de nascimento : 2014-02-14\nDist\u00E2ncia Total : 0.0\nDinheiro gasto/ganho : 0.0\nN\u00FAmero de viagens :0\nDisponibilidade : true\nClassifica\u00E7\u00E3o : 0.0\nGrau de cumprimento : 1.0\nN\u00FAmero de classifica\u00E7\u00F5es : 0\nVe\u00EDculo : null\nDesvio total : 0.0\n", string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "", "", localDate0, (-791.25360530683), "Viagem de (");
      driver0.setTimeCompliance((-1925.39387913872));
      assertEquals((-1925.39387913872), driver0.getTimeCompliance(), 0.01);
  }
}
